---
- name: Install OpenVPN and Easy-RSA
  apt:
    name:
      - openvpn
      - easy-rsa
    state: present
    update-cache: true

- name: Make Easy-RSA directory
  block:
    - name: Check if directory exists
      stat:
        path: "{{ easy_rsa_path }}"
      register: easy_rsa_exists

    - name: Create directory if not exist
      command: make-cadir "{{ easy_rsa_path }}"
      become_user: vagrant
      when: not easy_rsa_exists.stat.exists

- name: Make PKI directory
  block:
    - name: Check if directory exists
      stat:
        path: "{{ easy_rsa_path }}/pki"
      register: pki_exists

    - name: Create directory if not exist
      command: ./easyrsa init-pki
      args:
        chdir: "{{ easy_rsa_path }}"
      become_user: vagrant
      when: not pki_exists.stat.exists

- name: Create CA and server certs
  block:
    - name: Check if CA cert exists
      stat:
        path: "{{ easy_rsa_pki_path }}/ca.crt"
      register: ca_cert

    - name: Check if server cert exists
      stat:
        path: "{{ easy_rsa_pki_path }}/issued/server.crt"
      register: server_cert

    - name: Check if private key exists
      stat:
        path: "{{ easy_rsa_pki_path }}/private/server.key"
      register: server_key

    - name: Check if Diffie-Hellman params exist
      stat:
        path: "{{ easy_rsa_pki_path }}/dh.pem"
      register: dh_params

    - name: Check if TLS key exists
      stat:
        path: "{{ easy_rsa_pki_path }}/ta.key"
      register: tls_key

    - name: Create CA if not exist
      shell: echo "openvpn_ca" | ./easyrsa build-ca nopass
      args:
        chdir: "{{ easy_rsa_path }}"
      become_user: vagrant
      when: not ca_cert.stat.exists

    - name: Create server cert if not exist
      shell: echo "openvpn_server" | ./easyrsa gen-req server nopass
      args:
        chdir: "{{ easy_rsa_path }}"
      become_user: vagrant
      when: not server_cert.stat.exists

    - name: sign server if not exist
      shell: echo "yes" | ./easyrsa sign-req server server
      args:
        chdir: "{{ easy_rsa_path }}"
      become_user: vagrant
      when: not server_cert.stat.exists

    - name: gen Diffie-Hellman params if not exist
      command: ./easyrsa gen-dh
      args:
        chdir: "{{ easy_rsa_path }}"
      become_user: vagrant
      when: not dh_params.stat.exists

    - name: gen TLS key if not exist
      command: openvpn --genkey --secret pki/ta.key
      args:
        chdir: "{{ easy_rsa_path }}"
      become_user: vagrant
      when: not tls_key.stat.exists

- name: Check if OpenVPN dir exists
  file:
    path: /etc/openvpn
    state: directory
    mode: '0755'

- name: Copy files to OpenVPN
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_config_path }}"
    remote_src: yes
  with_items:
    - "{{ easy_rsa_pki_path }}/ca.crt"
    - "{{ easy_rsa_pki_path }}/issued/server.crt"
    - "{{ easy_rsa_pki_path }}/private/server.key"
    - "{{ easy_rsa_pki_path }}/dh.pem"
    - "{{ easy_rsa_pki_path }}/ta.key"

- name: Apply OpenVPN server cfg
  template:
    src: "{{ openvpn_server_config }}"
    dest: /etc/openvpn/server.conf

- name: Start OpenVPN server
  systemd:
    name: openvpn@server
    state: started
    enabled: yes

- name: Create client cfg
  template:
    src: "{{ openvpn_client_config }}"
    dest: "client.ovpn"
